<a href="https://colab.research.google.com/github/ndminh2003/SMS_Spam_WebFlask_Classifier/blob/master/Data_Collection_And_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
table_1 = pd.read_csv("spam.csv", encoding='windows-1252')
table_1.head()

df_table_1 = table_1.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)
df_table_1.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df_final_1 = df_table_1.rename(columns={"v1": "Label", "v2": "Text"}, errors="raise")
df_final_1.head()

  Label                                               Text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
table_2 = pd.read_csv("spamraw.csv", encoding='utf-8')
table_2.head()

   type                                               text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or £10,000 ...
4  spam  okmail: Dear Dave this is your final notice to...

In [ ]:
df_final_2 = table_2.rename(columns={"type": "Label", "text": "Text"}, errors="raise")
df_final_2.head()

  Label                                               Text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or £10,000 ...
4  spam  okmail: Dear Dave this is your final notice to...

In [ ]:
df_sample = pd.concat([df_final_1, df_final_2])
df_sample.head()

  Label                                               Text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df_sample1 = df_sample.sample(frac = 1)
df_sample1.head()

     Label                                               Text
5361   ham         Yep get with the program. You're slacking.
4681   ham                       Aaooooright are you at work?
4614  spam  Sunshine Quiz! Win a super Sony DVD recorder i...
3765   ham  Yeah work is fine, started last week, all the ...
1289   ham                      Nope, I'm still in the market

In [ ]:
df = df_sample1.reset_index(drop=True)
df.head()

  Label                                               Text
0   ham         Yep get with the program. You're slacking.
1   ham                       Aaooooright are you at work?
2  spam  Sunshine Quiz! Win a super Sony DVD recorder i...
3   ham  Yeah work is fine, started last week, all the ...
4   ham                      Nope, I'm still in the market

In [ ]:
df_final = df.replace({'Label' : { 'ham' : 0, 'spam' : 1}})
df_final.head()

   Label                                               Text
0      0         Yep get with the program. You're slacking.
1      0                       Aaooooright are you at work?
2      1  Sunshine Quiz! Win a super Sony DVD recorder i...
3      0  Yeah work is fine, started last week, all the ...
4      0                      Nope, I'm still in the market

In [ ]:
df_final.to_csv('final_data.csv', index=False)